# users/exceptions.py

class UserNotFoundException(Exception):
    """Raised when a user is not found in the system."""
    pass
